FROM node:22-alpine

# Install Nestjs cli
RUN npm install -g @nestjs/cli

# Set working directory
WORKDIR /app

# Copy only package files first (para cache eficiente)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose API port
EXPOSE 3000

# Command to run the application in development mode with hot reloading
CMD ["npm", "run", "start:dev"]
